### ISSUE TITLE
Unnecessary try...catch

### ISSUE THREAD

**Issue by SFGrenade** [Nearrin/HollowKnight.AbsoluteZote#3]
but if you do need them i suggest having them inside of the foreach loops
https://github.com/yunjord/HollowKnight.AbsoluteZote/blob/cfad507b2016d5b868ba67416b0eec7c9023e885/AbsoluteZote/AbsoluteZote.cs#L76-L167

**Comment by yunjord** [comment]
If I don't use these try...catch, I won't be able to see any error message in modlog.txt when the code failed. (The function just returned silently.) Not sure if this is because I didn't setup correctly.
