### ISSUE TITLE
Redundant null check

### ISSUE THREAD

**Issue by SFGrenade** [Nearrin/HollowKnight.AbsoluteZote#4]
because it's `FirstOrDefault`, it will never return `null`, but `default` instead.
also applies to the int and bool things as well.
https://github.com/yunjord/HollowKnight.AbsoluteZote/blob/cfad507b2016d5b868ba67416b0eec7c9023e885/AbsoluteZote/FSM.cs#L71-L73

**Comment by Nearrin** [comment]
I don't know why but actually it did return null when called with a name the first time. I have just printed out log to confirm this. Otherwise my mod won't work anyway because I need the variable values to be memorized.
